### ISSUE TITLE
Verbose output on ctrl+c exit

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/shinigami#77]
I hit `ctrl+c` before any of the ssh connections were established and got the error message below. This information should have been caught by the exception handling in the `Application.execute` method. For some reason, it was dumped to the console instead.

Fix the error handling so users aren't assaulted by super long error messages after a keyboard interrupt.

The output:

```
Exception ignored in: <coroutine object _connect at 0x7fb3480b4640>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 449, in _connect
    conn.abort()
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 2559, in abort
    self._force_close(None)
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 1028, in _force_close
    self._transport.abort()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 678, in abort
    self._force_close(None)
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 729, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb3480b44c0>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb3480b4940>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb3480b41c0>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb3480b4ac0>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb3480b47c0>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb347ec4140>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb347ec42c0>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb3480b4dc0>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb3480b4f40>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb347ec4440>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb347ec45c0>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb3480b4c40>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb347ec4740>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb347ec48c0>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb347ec4ac0>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object _connect at 0x7fb347ec4c40>
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/crc-shinigami/lib64/python3.9/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1122, in _create_connection_transport
    transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
(base) (02:21 PM) ~: shinigami -vvv --version
```

**Comment by djperrefort** [comment]
After digging into this, it looks like a byproduct of how coroutines are spun up that bypasses the logging. This is a rare edge case that needs to be timed very carefully to coincide with the coroutine creation. Closing as won't fix.
